class Support(object):

    feature_dict = {
           'en-US': ('punctuation', 'boost', ('default', 'command_and_search')),
        'ar-AE': {'punctuation', 'diarization', 'boost', 'enhanced',
                   ('default', 'command_and_search')},
    'ar-BH': {'punctuation', 'diarization',
               'boost', 'enhanced',
               ('default', 'command_and_search')},
    'ar-DZ': {'punctuation', 'diarization',
               'boost', 'enhanced',
             ('default', 'command_and_search')},
    'ar-EG': {'punctuation', 'diarization',
               'boost', 'enhanced',
             ('default', 'command_and_search')},
    'ar-IL': {'punctuation', 'diarization',
               'boost', 'enhanced',
             ('default', 'command_and_search')},
    'ar-IQ': {'punctuation', 'diarization',
               'boost', 'enhanced',
             ('default', 'command_and_search')},
    'ar-JO': {'punctuation', 'diarization',
               'boost', 'enhanced',
             ('default', 'command_and_search')},
    'ar-KW': {'punctuation', 'diarization',
               'boost', 'enhanced',
             ('default', 'command_and_search')},
    'ar-LB': {'punctuation', 'diarization',
               'boost', 'enhanced',
             ('default', 'command_and_search')},
    'ar-MA': {'punctuation', 'diarization',
               'boost', 'enhanced',
             ('default', 'command_and_search')},
    'ar-OM': {'punctuation', 'diarization',
               'boost', 'enhanced',
             ('default', 'command_and_search')},
    'ar-PS': {'punctuation', 'diarization',
               'boost', 'enhanced',
             ('default', 'command_and_search')},
    'ar-QA': {'punctuation', 'diarization',
               'boost', 'enhanced',
             ('default', 'command_and_search')},
    'ar-SA': {'punctuation', 'diarization',
               'boost', 'enhanced',
             ('default', 'command_and_search')},
    'ar-TN': {'punctuation', 'diarization',
               'boost', 'enhanced',
             ('default', 'command_and_search')},
    'de-DE': {'punctuation', 'diarization',
               'boost', 'enhanced',
             ('default', 'command_and_search')},
    'en-AU': {'punctuation', 'diarization',
               'boost', 'enhanced',
             ('default', 'command_and_search')},
    'en-GB': {'punctuation', 'diarization',
               'boost', 'enhanced',
             ('default', 'command_and_search', 'phone_call')},
    'en-GH': {'punctuation', 'diarization',
               'boost', 'enhanced',
             ('default', 'command_and_search')},
    'en-IE': {'punctuation', 'diarization',
               'boost', 'enhanced',
             ('default', 'command_and_search')},
    'en-IN': {'punctuation', 'diarization',
               'boost', 'enhanced',
             ('default', 'command_and_search')}
    }


    def get_feature_dict(self):
        return self.feature_dict


